name: Release

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0

      - name: Install gems
        run: |-
          bundle config set --local deployment true
          bundle install

      - name: Install cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1

      - name: Configure RubyGems credentials
        uses: rubygems/configure-rubygems-credentials@f623036f13ddde19c3dc555bdcc20059c18dc042 # main

      - name: Push release to RubyGems
        run: bin/rake release:push
