name: Release

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0

      - name: Install gems
        run: |-
          bundle config set --local deployment true
          bundle install

      - name: Release
        uses: rubygems/release-gem@e9a6361a0b14562539327c2a02373edc56dd3169 # v1.1.4
